Repository vaaibhavsharma/quizApplication, pull requests merged in 2022-10, with the labels that each got.

#4 Changed Logo and updated README
  README.md
  gitassets/logo.png
Labels: hacktoberfest

#8 Redo README.md
  README.md
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#12 Dockerized whole application (Compose used).
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement, hacktoberfest, HACKTOBERFEST-ACCEPTED
